name: Feature Request
description: Suggest a new feature or improvement
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your suggestion! Please describe the feature you would like to see.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: A clear description of the problem or gap this feature would address.
      placeholder: 'I find it difficult to... / There is no way to...'
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: A clear description of what you would like to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches or workarounds you have considered.

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other relevant context, screenshots, or examples.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues and this is not a duplicate.
          required: true
